kind: Service
apiVersion: v1
metadata:
  name: jenkins-lb
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: jenkins-leader
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
